# Generated by Django 6.0.1 on 2026-01-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azure_id', models.CharField(max_length=512, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('resource_group', models.CharField(max_length=128)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('vm_size', models.CharField(blank=True, max_length=64, null=True)),
                ('os_type', models.CharField(blank=True, max_length=32, null=True)),
                ('computer_name', models.CharField(blank=True, max_length=128, null=True)),
                ('power_state', models.CharField(blank=True, max_length=32, null=True)),
                ('private_ips', models.JSONField(default=list)),
                ('public_ips', models.JSONField(default=list)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
