# Generated by Django 6.0.1 on 2026-01-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_virtualmachine_deleted_at_virtualmachine_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azure_id', models.CharField(max_length=512, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('resource_group', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(max_length=256)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('kind', models.CharField(blank=True, max_length=128, null=True)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='private_ips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='public_ips',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
