# Generated by Django 6.0.1 on 2026-01-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_azureresource_alter_virtualmachine_private_ips_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azureresource',
            old_name='details',
            new_name='component_summary',
        ),
        migrations.AddField(
            model_name='azureresource',
            name='detail_api_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='azureresource',
            name='raw_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='azureresource',
            name='tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='private_ips',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='public_ips',
            field=models.JSONField(default=list),
        ),
    ]
